Updates deployment to deploy latest code for notifications
- updates acceptance tests
- adds zero-downtime deployment process

[#94139074]

diff --git a/jobs/deploy-notifications/templates/deploy.sh.erb b/jobs/deploy-notifications/templates/deploy.sh.erb
--- a/jobs/deploy-notifications/templates/deploy.sh.erb
+++ b/jobs/deploy-notifications/templates/deploy.sh.erb
@@ -1,21 +1,45 @@
-#!/bin/bash
-set -e -x
+#!/bin/bash -exu
 
 export PATH="/var/vcap/packages/cf_cli/bin:$PATH"
 
-export SCHEME=https
-export DOMAIN=<%= properties.domain %>
-export ADMIN_USER=<%= properties.notifications.cf.admin_user %>
-export ADMIN_PASSWORD=<%= properties.notifications.cf.admin_password %>
-export API_ENDPOINT=$SCHEME://api.$DOMAIN
-export ORG=system
-export SPACE=notifications-service
-export QUOTA=notifications-service
-export APP_NAME=notifications
-export APP_DOMAIN=<%= properties.notifications.app_domain %>
+SCHEME=https
+DOMAIN=<%= properties.domain %>
+ADMIN_USER=<%= properties.notifications.cf.admin_user %>
+ADMIN_PASSWORD=<%= properties.notifications.cf.admin_password %>
+API_ENDPOINT=$SCHEME://api.$DOMAIN
+ORG=system
+SPACE=notifications-service
+QUOTA=notifications-service
+APP_NAME=notifications
+APP_DOMAIN=<%= properties.notifications.app_domain %>
 
 export CF_HOME=`pwd`/home/cf
 mkdir -p $CF_HOME
+
+function validate_database_connection_count() {
+  if [[ "<%= properties.notifications.database.max_open_connections %>" -eq "0" ]]; then
+    echo "The database max_open_connections value cannot be unlimited"
+    exit 1
+  fi
+
+  if (( "<%= properties.notifications.database.max_open_connections %>" < "<%= properties.notifications.instance_count %>" )); then
+    echo "The database max_open_connections value must be greater than instance_count value"
+    exit 1
+  fi
+}
+
+function validate_smtp_config() {
+  warning_message="The notifications service was not deployed because SMTP host or port is missing"
+  if [[ -z "<%= properties.notifications.smtp.host %>" ]]; then
+    echo $warning_message
+    exit 1
+  fi
+
+  if [[ -z "<%= properties.notifications.smtp.port %>" ]]; then
+    echo $warning_message
+    exit 1
+  fi
+}
 
 function authenticate_and_target() {
   cf api $API_ENDPOINT <% if properties.ssl.skip_cert_verify %>--skip-ssl-validation<% end %>
@@ -26,51 +50,79 @@ function authenticate_and_target() {
   cf target -s $SPACE
 }
 
-function create_quota() {
-  cf create-quota $QUOTA -m 1G -r 10 -s 10
-  cf update-quota $QUOTA -m 1G -r 10 -s 10 --disallow-paid-service-plans
-  cf set-quota $ORG $QUOTA
-}
-
-function add_env_vars() {
-  cf set-env $APP_NAME SMTP_AUTH_MECHANISM "<%= properties.notifications.smtp.auth_mechanism %>"
-  cf set-env $APP_NAME SMTP_CRAMMD5_SECRET "<%= properties.notifications.smtp.crammd5_secret %>"
-  cf set-env $APP_NAME SMTP_HOST "<%= properties.notifications.smtp.host %>"
-  cf set-env $APP_NAME SMTP_PASS "<%= properties.notifications.smtp.pass %>"
-  cf set-env $APP_NAME SMTP_PORT "<%= properties.notifications.smtp.port %>"
-  cf set-env $APP_NAME SMTP_USER "<%= properties.notifications.smtp.user %>"
-  cf set-env $APP_NAME SMTP_TLS "<%= properties.notifications.smtp.tls %>"
-  cf set-env $APP_NAME SENDER "<%= properties.notifications.sender %>"
-  cf set-env $APP_NAME DOMAIN "<%= properties.domain %>"
-  cf set-env $APP_NAME UAA_CLIENT_ID "<%= properties.notifications.uaa.client_id %>"
-  cf set-env $APP_NAME UAA_CLIENT_SECRET "<%= properties.notifications.uaa.client_secret %>"
-  cf set-env $APP_NAME VERIFY_SSL "<%= !properties.ssl.skip_cert_verify %>"
-  cf set-env $APP_NAME ROOT_PATH "\$HOME"
-  cf set-env $APP_NAME DATABASE_URL "<%= properties.notifications.database.url %>"
-  cf set-env $APP_NAME GOBBLE_MIGRATIONS_DIR "\$HOME/gobble/migrations"
-  cf set-env $APP_NAME ENCRYPTION_KEY "<%= properties.notifications.encryption_key %>"
-  cf set-env $APP_NAME DB_MAX_OPEN_CONNS "<%= properties.notifications.database.max_open_connections %>"
-  cf set-env $APP_NAME DIEGO_STAGE_BETA true
-
-  cf set-env $APP_NAME UAA_HOST $SCHEME://uaa.$DOMAIN
-  cf set-env $APP_NAME CC_HOST $SCHEME://api.$DOMAIN
-}
-
-function push_app() {
+function create_manifest() {
   pushd /var/vcap/packages/notifications
-    mkdir -p /var/vcap/data/tmp
-    export TMPDIR=/var/vcap/data/tmp
-    cf push $APP_NAME --no-start -d $APP_DOMAIN
+    cat << EOF > manifest.yml
+---
+applications:
+  - name: notifications
+    command: bin/notifications
+    memory: 64M
+env:
+  DOMAIN: "<%= properties.domain %>"
+  UAA_CLIENT_ID: "<%= properties.notifications.uaa.client_id %>"
+  UAA_CLIENT_SECRET: "<%= properties.notifications.uaa.client_secret %>"
+  VERIFY_SSL: "<%= !properties.ssl.skip_cert_verify %>"
+  ROOT_PATH: "\$HOME"
+  ENCRYPTION_KEY: "<%= properties.notifications.encryption_key %>"
+  UAA_HOST: $SCHEME://uaa.$DOMAIN
+  CC_HOST: $SCHEME://api.$DOMAIN
+  SMTP_AUTH_MECHANISM: "<%= properties.notifications.smtp.auth_mechanism %>"
+  SMTP_CRAMMD5_SECRET: "<%= properties.notifications.smtp.crammd5_secret %>"
+  SMTP_HOST: "<%= properties.notifications.smtp.host %>"
+  SMTP_PASS: "<%= properties.notifications.smtp.pass %>"
+  SMTP_PORT: "<%= properties.notifications.smtp.port %>"
+  SMTP_USER: "<%= properties.notifications.smtp.user %>"
+  SMTP_TLS: "<%= properties.notifications.smtp.tls %>"
+  SENDER: "<%= properties.notifications.sender %>"
+  DATABASE_URL: "<%= properties.notifications.database.url %>"
+  GOBBLE_MIGRATIONS_DIR: "\$HOME/gobble/migrations"
+  DB_MAX_OPEN_CONNS: "<%= properties.notifications.database.max_open_connections / properties.notifications.instance_count %>"
+EOF
+
+  cat manifest.yml
   popd
 }
 
-function boot_app() {
-  cf restart $APP_NAME
+function push_app() {
+  pushd /var/vcap/packages/notifications > /dev/null
+    mkdir -p /var/vcap/data/tmp
+    export TMPDIR=/var/vcap/data/tmp
+
+    set +e
+      cf app $APP_NAME --guid
+      local exit_code=$?
+    set -e
+
+    if [[ $exit_code -ne 0 ]]; then
+      cf push -i 1
+    else
+      cf install-plugin /var/vcap/packages/cf_cli/plugins/autopilot
+      cf zero-downtime-push $APP_NAME -f manifest.yml -p .
+    fi
+  popd > /dev/null
+}
+
+function scale_app_down() {
+  set +e
+    cf app $APP_NAME --guid
+    local exit_code=$?
+  set -e
+
+  if [[ $exit_code -eq 0 ]]; then
+    cf scale $APP_NAME -i 1
+  fi
+}
+
+function scale_app_up() {
+  cf scale $APP_NAME -i <%= properties.notifications.instance_count %>
 }
 
 cf -v
+validate_database_connection_count
+validate_smtp_config
 authenticate_and_target
-create_quota
+create_manifest
+scale_app_down
 push_app
-add_env_vars
-boot_app
+scale_app_up
